#!/bin/bash
# Cesare de Filippo, MPI-EVA
# modified on 12-August-2013 
#$ -S /bin/bash
#$ -cwd
#$ -q all.q
# load personal profile
#$ -V
#$ -R y
#$ -M barbara_domingues@eva.mpg.de
#$ -m e
#$ -l h_vmem=1G,s_vmem=1G



for i in {1..1000};

do



#0.3
/mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/BALLET -T1 100 /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/DivFile_neu /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/PolySubFile_neu  /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/bs_f0.3_SNPFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/bs_f0.3_RecFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/OutFile_T1_f0.3_bs_$i

/mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/BALLET -T1 100 /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/DivFile_neu /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/PolySubFile_neu  /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/bs_f0.3_SNPFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/bs_f0.3_RecFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/OutFile_T1_f0.3_bs_$i

/mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/BALLET -T1 100 /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/DivFile_neu /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/PolySubFile_neu  /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/bs_f0.3_SNPFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/bs_f0.3_RecFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/OutFile_T1_f0.3_bs_$i

/mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/BALLET -T1 100 /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/DivFile_neu /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/PolySubFile_neu  /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/bs_f0.3_SNPFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/bs_f0.3_RecFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/OutFile_T1_f0.3_bs_$i



#0.4
/mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/BALLET -T1 100 /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/DivFile_neu /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/PolySubFile_neu  /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/bs_f0.4_SNPFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/bs_f0.4_RecFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/OutFile_T1_f0.4_bs_$i

/mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/BALLET -T1 100 /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/DivFile_neu /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/PolySubFile_neu  /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/bs_f0.4_SNPFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/bs_f0.4_RecFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/OutFile_T1_f0.4_bs_$i

/mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/BALLET -T1 100 /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/DivFile_neu /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/PolySubFile_neu  /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/bs_f0.4_SNPFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/bs_f0.4_RecFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/OutFile_T1_f0.4_bs_$i

/mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/BALLET -T1 100 /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/DivFile_neu /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/PolySubFile_neu  /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/bs_f0.4_SNPFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/bs_f0.4_RecFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/OutFile_T1_f0.4_bs_$i


#0.5
/mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/BALLET -T1 100 /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/DivFile_neu /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/PolySubFile_neu  /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/bs_f0.5_SNPFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/bs_f0.5_RecFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/OutFile_T1_f0.5_bs_$i

/mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/BALLET -T1 100 /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/DivFile_neu /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/PolySubFile_neu  /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/bs_f0.5_SNPFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/bs_f0.5_RecFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp/Tbs3/OutFile_T1_f0.5_bs_$i


/mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/BALLET -T1 100 /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/DivFile_neu /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/PolySubFile_neu  /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/bs_f0.5_SNPFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/bs_f0.5_RecFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/OutFile_T1_f0.5_bs_$i

/mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/BALLET -T1 100 /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/DivFile_neu /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/PolySubFile_neu  /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/bs_f0.5_SNPFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/bs_f0.5_RecFile$i /mnt/sequencedb/PopGen/barbara/NCV_dir_package/BALLET/tmp_Eur/Tbs3/OutFile_T1_f0.5_bs_$i

done
