#!/bin/bash
# Cesare de Filippo, MPI-EVA
# modified on 12-August-2013 
#$ -S /bin/bash
#$ -cwd
#$ -q all.q
# load personal profile
#$ -V
#$ -R y
#$ -M barbara_domingues@eva.mpg.de
#$ -m e
#$ -l h_vmem=1G,s_vmem=1G



for i in {1..1000};

do




/mnt/sequencedb/PopGen/barbara/BALLET/BALLET -T2 100 DivFile_neu PolySubFile_neu SpectFile_neu /mnt/sequencedb/PopGen/barbara/BALLET/tmp_Eur/bs_f0.3_SNPFile$i /mnt/sequencedb/PopGen/barbara/BALLET/tmp_Eur/bs_f0.3_RecFile$i /home/barbara_domingues/Downloads/simulated_spectra/ /mnt/sequencedb/PopGen/barbara/BALLET/tmp_Eur/OutFile_T2_f0.3_bs_$i

/mnt/sequencedb/PopGen/barbara/BALLET/BALLET -T2 100 DivFile_neu PolySubFile_neu SpectFile_neu /mnt/sequencedb/PopGen/barbara/BALLET/tmp_Eur/bs_f0.4_SNPFile$i /mnt/sequencedb/PopGen/barbara/BALLET/tmp_Eur/bs_f0.4_RecFile$i /home/barbara_domingues/Downloads/simulated_spectra/ /mnt/sequencedb/PopGen/barbara/BALLET/tmp_Eur/OutFile_T2_f0.4_bs_$i

/mnt/sequencedb/PopGen/barbara/BALLET/BALLET -T2 100 DivFile_neu PolySubFile_neu SpectFile_neu /mnt/sequencedb/PopGen/barbara/BALLET/tmp_Eur/bs_f0.5_SNPFile$i /mnt/sequencedb/PopGen/barbara/BALLET/tmp_Eur/bs_f0.5_RecFile$i /home/barbara_domingues/Downloads/simulated_spectra/ /mnt/sequencedb/PopGen/barbara/BALLET/tmp_Eur/OutFile_T2_f0.5_bs_$i







done